name: DiziPal Kazıyıcı

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Her gün gece yarısı çalışır
  workflow_dispatch:

jobs:
  kazi:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Depoya yazma izni

    steps:
      - name: Kodu çek
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Tüm geçmişi çek

      - name: Python'u kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Bağımlılıkları yükle
        run: |
          python -m pip install --upgrade pip
          pip install requests cloudscraper beautifulsoup4 pycryptodome PySocks

      - name: Kazıyıcıyı çalıştır
        run: |
          python dizipal.py

      - name: Sonuçları kaydet ve gönder
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Kazınan veriler güncellendi" || echo "Kaydedilecek değişiklik yok"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
