name: DiziPal Kazıyıcı

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manuel çalıştırma için

jobs:
  kazi:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Depoya yazma izni

    steps:
      - name: Kodu çek
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Tüm geçmişi çek

      - name: Python'u kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Bağımlılıkları yükle
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests beautifulsoup4 pycryptodome PySocks
          playwright install --with-deps

      - name: Kazıyıcıyı çalıştır
        run: |
          python dizipal.py

      - name: Sonuçları kaydet ve gönder
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Kazınan veriler güncellendi" || echo "Kaydedilecek değişiklik yok"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
