name: Dizipal M3U8 Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Her gün saat 00:00'da çalıştır (UTC)
  workflow_dispatch: # GitHub arayüzünden manuel çalıştırmaya izin verir

jobs:
  scrape:
    runs-on: ubuntu-latest # Ubuntu i\u015Fletim sisteminde \u00E7al\u0131\u015Ft\u0131r

    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Python 3'un en yeni s\u00FCr\u00FCm\u00FCn\u00FC kullan

      - name: Gerekli Chromium Bağımlılıklarını Kur
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Python Bağımlılıklarını Kur
        run: pip install -r requirements.txt

      - name: Scraper'ı Çalıştır
        # Python scriptinin \u00E7\u0131kt\u0131s\u0131n\u0131 bir dosyaya y\u00F6nlendir
        run: python main.py

      - name: m3u8 Linklerini Artifact Olarak Yükle
        uses: actions/upload-artifact@v4
        with:
          name: dizipal-m3u8-links
          path: m3u8_links.txt
